version: 2.1

# See https://circleci.com/orbs/registry/orb/circleci/gcp-gcr
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1

jobs:
  simpleprophet-pypi-deploy:
    docker:
    - image: python:3.8
    working_directory: ~/project/simpleprophet
    steps:
    - checkout:
        path: ~/project
    - run:
        name: Upload to PyPI via Twine
        # This step relies on several environment variables provided to the
        # build job via CircleCI configuration:
        #   TWINE_USERNAME
        #   TWINE_PASSWORD
        # The particular creds here correspond to a token provisioned from
        # the Jeff.Klukas PyPI account allowing upload access for simpleprophet.
        command: |
          pip install twine
          python setup.py sdist bdist_wheel
          twine upload dist/*

workflows:
  version: 2
  simpleprophet-build:
    jobs:
    - gcp-gcr/build-and-push-image:
        # Context defined in https://bugzilla.mozilla.org/show_bug.cgi?id=1608958
        context: data-eng-airflow-gcr
        dockerfile: simpleprophet/Dockerfile
        path: simpleprophet
        image: simpleprophet
        filters:
          branches:
            only: main
    - simpleprophet-pypi-deploy:
        filters:
          tags:
            only: /[0-9.]*/
          branches:
            ignore: /.*/
  anomdtct-build:
    jobs:
    - gcp-gcr/build-and-push-image:
        # Context defined in https://bugzilla.mozilla.org/show_bug.cgi?id=1608958
        context: data-eng-airflow-gcr
        dockerfile: anomdtct/Dockerfile
        path: anomdtct
        image: anomdtct
        filters:
          branches:
            only: main
