version: 2.1

# See https://circleci.com/orbs/registry/orb/circleci/gcp-gcr
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1

workflows:
  version: 2
  build:
    jobs:
    - gcp-gcr/build-and-push-image:
        # We rely on several environment variables provided to the CircleCI
        # environment for authentication to GCR in a dataops sandbox project;
        # the service account we provide has GCS write access per
        # https://cloud.google.com/container-registry/docs/access-control
        dockerfile: simpleprophet/Dockerfile
        path: simpleprophet
        image: simpleprophet
        filters:
          branches:
            only: master
