version: 2.1

# See https://circleci.com/orbs/registry/orb/circleci/gcp-gcr
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1

jobs:
  simpleprophet-pypi-deploy:
    docker:
    - image: python:3.8
    working_directory: ~/project/simpleprophet
    steps:
    - checkout:
        path: ~/project
    - run:
        name: Upload to PyPI via Twine
        # This step relies on several environment variables provided to the
        # build job via CircleCI configuration:
        #   TWINE_USERNAME
        #   TWINE_PASSWORD
        # The particular creds here correspond to a token provisioned from
        # the Jeff.Klukas PyPI account allowing upload access for simpleprophet.
        command: |
          pip install twine
          python setup.py sdist bdist_wheel
          twine upload dist/*

workflows:
  version: 2
  build:
    jobs:
    - gcp-gcr/build-and-push-image:
        # This step relies on several environment variables provided to the
        # build job via CircleCI configuration:
        #   GCLOUD_SERVICE_KEY
        #   GOOGLE_PROJECT_ID
        #   GOOGLE_COMPUTE_ZONE
        # We provisioned a dataops sandbox project specifically for this
        # repository, enabled the GCR API, and provisioned a service account
        # with read and write access to GCS per
        #   https://cloud.google.com/container-registry/docs/access-control
        # We also have marked the repository in GCR as public via the GCP console
        # so that arbitrary users and applications can access the images.
        dockerfile: simpleprophet/Dockerfile
        path: simpleprophet
        image: simpleprophet
        filters:
          branches:
            only: master
    - simpleprophet-pypi-deploy:
        filters:
          tags:
            only: /[0-9.]*/
          branches:
            ignore: /.*/
