#!/usr/bin/env python3

"""
Entrypoint script for running pipeline.replace_single_day.
"""

import argparse

from anomdtct.pipeline import replace_single_day
from google.cloud import bigquery
from google.cloud.bigquery_storage_v1beta1 import BigQueryStorageClient


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("dt", help="model date to process")
parser.add_argument("--project-id", "--project_id", help="destination project")
parser.add_argument("--dataset-id", "--dataset_id", help="destination dataset")
parser.add_argument("--table-id", "--table_id", help="destination table")
parser.add_argument("--spreadsheet-id", "--spreadsheet_id", help="ID of the Google spreadsheet")
args = parser.parse_args()
kwargs = {k: v for k, v in vars(args).items() if v is not None}

bq_client = bigquery.Client(args.project_id)
bq_storage_client = BigQueryStorageClient()

replace_single_day(bq_client, bq_storage_client, **kwargs)
